### ISSUE TITLE
Google search links to 404

### ISSUE THREAD

**Issue by nxb9626** [peterkos/peterkos.github.io#12]
When clicking the first link to your website, it finds the peterkos.me/posts, which leads to a 404 page. 

The google search: https://www.google.com/search?q=peter+kos+blog
![image](https://user-images.githubusercontent.com/35909846/146148242-9892948b-7faa-46a3-9350-3b554bb490c1.png)

It finds /posts rather than the home page.
![image](https://user-images.githubusercontent.com/35909846/146148162-960c30a6-85cf-4d25-a0d5-53d7ac59ac1e.png)

**Comment by peterkos** [comment]
HAH it works now big google is big friend

(Moving to the [new theme](#13) i think helped :)
